@startuml usecase_main
left to right direction
skinparam actorStyle awesome
:admin: 
rectangle system{
    
    rectangle login{
        (entrar)
    }
    rectangle main{
        
        (cadastrar\nmembro) as cd 
        (editar\nmembro) as edit 
        (remover\nmembro) as rm
        (relatorios\n) as rl

        ' cd -down-> edit
        ' edit -down-> rm
        ' rm -down-> rl
        }
        
    rectangle reports{
        note top of reports: Conteudo do\n Banco de dados
    }
}
admin --> login 
entrar --> cd : <<include>>
rl --> reports
@enduml
